
###
GET http://localhost:3000

###
POST http://localhost:3000/users
content-type: application/json

{
    "id": null,
    "fullName": "Franck Duval",
    "birthday":"2004-01-01",
    "isActive":true
}


###
GET http://localhost:3000/users/5
