
###
GET http://localhost:3000

###
POST http://localhost:3000/users
content-type: application/json

{
    "id": null,
    "fullName": "Glaby Lacarte",
    "birthday":"1984-01-01",
    "isActive":true
}


###
GET http://localhost:3000/users/1
